---
- name: Create loadbalancer
  block:
    - name: Create haproxy container
      ansible.builtin.include_tasks:
        file: "{{ group_names | first }}-create.yml"
      when: controlplane_ips | count > 1
  rescue:
    - name: Destroy loadbalancer
      ansible.builtin.include_tasks:
        file: "{{ group_names | first }}-destroy.yml"
