---
- name: Create loadbalancer
  block:
    - name: Create persistence folder
      ansible.builtin.file:
        path: "{{ persistence_folder }}"
        state: directory
        mode: "0755"
    - name: Create haproxy container
      ansible.builtin.include_tasks:
        file: "{{ group_names | first }}-create.yml"
  rescue:
    - name: Destroy loadbalancer
      ansible.builtin.include_tasks:
        file: "{{ group_names | first }}-destroy.yml"
