- name: Destroy container
  community.docker.docker_compose_v2:
    project_src: "{{ unraid_haproxy_compose_project }}"
    state: absent
  failed_when: false

- name: Remove appdata folder
  ansible.builtin.file:
    path: "{{ unraid_haproxy_appdata }}"
    state: absent
