- name: Create template VM
  ansible.builtin.shell:
    chdir: "{{ persistence_folder }}"
    cmd: |
      qm create {{ pve_template_vm_id }} --name k3s-template \
        --net0 virtio,bridge=vmbr0 --cpu host
      qm importdisk {{ pve_template_vm_id }} vm.qcow2 {{ pve_container_storage }}
      qm set {{ pve_template_vm_id }} --scsihw virtio-scsi-single \
        --scsi0 {{ pve_container_storage }}:{{ pve_template_vm_id }}/vm-{{ pve_template_vm_id }}-disk-0.raw
      qm set {{ pve_template_vm_id }} --ide2 {{ pve_container_storage }}:cloudinit
      qm set {{ pve_template_vm_id }} --boot order=scsi0
      qm set {{ pve_template_vm_id }} --serial0 socket --vga serial0
      qm set {{ pve_template_vm_id }} --sshkey <(echo '{{ ssh_key }}' && cat ~/.ssh/id_rsa.pub)
      qm resize {{ pve_template_vm_id }} scsi0 {{ pve_scos_template_add_storage }}
      qm template {{ pve_template_vm_id }}
    creates: /etc/pve/qemu-server/{{ pve_template_vm_id }}.conf
  args: # we need bash for process substitution
    executable: /bin/bash

- name: Create control plane VMs
  vars:
    template_id: "{{ pve_controlplane_ids_start_from + index }}"
  ansible.builtin.shell:
    cmd: |
      qm clone {{ pve_template_vm_id }} {{ template_id }} --name {{ controlplane_name }}{{ index }}
      qm set {{ template_id }} --net0 virtio,bridge=vmbr0,macaddr={{ controlplane_mac_addresses[index] }}
      qm set {{ template_id }} --cores {{ controlplane_cores }}
      qm set {{ template_id }} --memory {{ controlplane_memory }}
      qm set {{ template_id }} --agent {{ pve_controlplane_agent }}
      qm start {{ template_id }}
    creates: /etc/pve/qemu-server/{{ template_id }}.conf
  loop: "{{ controlplane_ips }}"
  loop_control:
    index_var: index
- name: Create worker VMs
  vars:
    template_id: "{{ pve_worker_ids_start_from + index }}"
  ansible.builtin.shell:
    cmd: |
      qm clone {{ pve_template_vm_id }} {{ template_id }} --name {{ worker_name }}{{ index }}
      qm set {{ template_id }} --net0 virtio,bridge=vmbr0,macaddr={{ worker_mac_addresses[index] }}
      qm set {{ template_id }} --cores {{ worker_cores }}
      qm set {{ template_id }} --memory {{ worker_memory }}
      qm set {{ template_id }} --agent {{ pve_worker_agent }}
      qm start {{ template_id }}
    creates: /etc/pve/qemu-server/{{ template_id }}.conf
  loop: "{{ worker_ips }}"
  loop_control:
    index_var: index
