- name: Destroy control planes
  vars:
    template_id: "{{ pve_controlplane_ids_start_from + index }}"
  ansible.builtin.shell:
    cmd: |
      qm stop {{ template_id }}
      qm destroy {{ template_id }}
    removes: /etc/pve/qemu-server/{{ template_id }}.conf
  register: destroy_vm
  loop: "{{ controlplane_ips }}"
  loop_control:
    index_var: index
- name: Destroy worker nodes
  vars:
    template_id: "{{ pve_worker_ids_start_from + index }}"
  ansible.builtin.shell:
    cmd: |
      qm stop {{ template_id }}
      qm destroy {{ template_id }}
    removes: /etc/pve/qemu-server/{{ template_id }}.conf
  register: destroy_vm
  loop: "{{ worker_ips }}"
  loop_control:
    index_var: index
- name: Destroy template machine
  ansible.builtin.command:
    cmd: qm destroy {{ pve_template_vm_id }}
    removes: /etc/pve/qemu-server/{{ pve_template_vm_id }}.conf
  register: destroy_vm
